### ISSUE TITLE
tsx and jsx support gone with last update

### ISSUE THREAD

**Issue by gutisalex** [Codium-ai/codiumai-jetbrains-release#41]
Version: 1.2.19

Issue: Not able to generate tests inside .tsx or .jsx files.

┆Issue is synchronized with this [Trello card](https://trello.com/c/sTf0ih8t) by [Unito](https://www.unito.io)

**Comment by ArtsiomCh** [comment]
Not sure I'm getting you. We don't have 1.2.19 version. Could you explain in more details please?

**Comment by wyiz75** [comment]
Hello @ArtsiomCh !

I will add some information on his ticket.

When you open a file which contain a React Functional component it doesn't show `Generate tests for the below function` as you can see on the screenshot below.

![Screenshot 2023-06-08 at 15 15 24](https://github.com/Codium-ai/codiumai-jetbrains-release/assets/106260504/9fa2e15f-4f18-441d-9b93-d59c53ad43da)

Thanks

**Comment by vdr-mm-josu** [comment]
@ArtsiomCh Since version 0.5.11 i can no longer create test from functional components.

**Comment by ArtsiomCh** [comment]
Aha, now I understand the issue. Will have a look tomorrow, I think I know what's the root cause.

**Comment by ArtsiomCh** [comment]
Will be fixed in upcoming (~Mon-Wed) 0.5.12 version
For now you can use attached 0.5.2-dev1 by installing it "from disk":
[codium-ai-plugin-0.5.12-dev1.zip](https://github.com/Codium-ai/codiumai-jetbrains-release/files/11705855/codium-ai-plugin-0.5.12-dev1.zip)
![image](https://github.com/Codium-ai/codiumai-jetbrains-release/assets/14268320/8feaec63-34f0-4706-ac3b-265319dd3b1a)

Thanks everyone for detailed explanation!
